# -*- coding: utf-8 -*-
"""Aula 2 - Python - Inteligencia Artificial Aplicada

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mm6Ug_OGJrz6X8VogkLSsoQE2FLZn5FF

# **Aula 2**
"""

import os
from google.colab import userdata
os.environ["GEMINI_API_KEY"] = userdata.get("GEMINI_API_KEY")

from google import genai

client = genai.Client()

respuesta = client.models.generate_content(model="gemini-2.5-flash", contents="Que es la IA")

print(respuesta.text)

print("*********************")

n = 1

while n <=100:
  print("*")
  n=n+1
print("Ya salimos del while")

chat = client.chats.create(model="gemini-2.5-flash")

respuesta = chat.send_message("Que es la IA")

print(respuesta)

respuesta =chat.send_message("Cuando se lanzo chatGPT")
print(respuesta.text)

chat.get_history()

prompt = input("Ingrese su pregunta: ")

while prompt != "fin":
  respuesta=chat.send_message(prompt)
  print(respuesta.text)
  prompt = input("Ingrese su pregunta (fin para terminar): ")

nombres = ["Juan","Laura","Fernando","Josefina","Pedro"]
# pos.       0       1         2          3        4
print(nombres)

print("El quinto elemento es:",nombres[4])

promedios = [8.5,6.5,7.3,9.5,6.3,2.5,4.8]
print(promedios[3])

n=0 #1

while n < len(promedios):
  promedios[n]=promedios[n]+1
  if promedios[n]>10:
     promedios[n]=10
  n=n+1
print("Los promedios mejorados son:",promedios)

print("Cantidad de elementos en la lista:",len(promedios))

promedios[-2]

nombres=["Maria Silva","Fernanda Castro","Juan Perez","Rodrigo Feliz","Juana Lala"]
print(nombres)

nombres[:3]

nombres.append("Rogelio Rodriguez")
print(nombres)

print("Cantidad de elementos:",len(nombres))

nombres.extend(["Mateo Perez","Laura Fernan"])
print(nombres)

nombres.append(["Juan Oroz","Pedro Pereyra"])

print(nombres)

nombres[8][1]

nombres[-1][-1]

nombres.remove("Maria Silva")

nombres

nombres.pop()
nombres

nombres.pop(2)
nombres

"""Diccionarios:

estudiantes=["clave":valor]
"""

nombres=["Maria Silva","Fernanda Castro","Juan Perez","Rodrigo Feliz","Juana Lala"]
promedios = [8.5,6.5,7.3,9.5,6.3,2.5,4.8]

estudiantes = {
    "Maria Silva":8.5,
    "Fernanda Castro":6.5,
    "Juan Perez":7.3,
    "Rodrigo Feliz":6.3,
    "Juaan Lala":2.5
}

print(nombres)
print(promedios)
print(estudiantes)

print(estudiantes["Maria Silva"])
print(estudiantes.get("Maria Silva"))

print(estudiantes.items())

estudiantes.pop("Maria Silva")
estudiantes

print(estudiantes.keys())

print(estudiantes.values())

persona= {
    "nombre":"Juan Perez",
    "edad":25,
    "materias":["Matematica","Literatura","Dibujo"]
}

print(persona)

estudiante1 = {
    "nombre":"Juan Perez","edad":25
    }

estudiante2 = {
    "nombre":"Laura Fernandez","edad":28
    }

print(estudiante1)
print(estudiante2)

lista_de_estudiantes= [
    {
    "nombre":"Juan Perez","edad":25
    },
    {
    "nombre":"Laura Fernandez","edad":28
    }
]

print(lista_de_estudiantes)

lista_de_estudiantes[1]

lista_de_estudiantes[1]["edad"]