# -*- coding: utf-8 -*-
"""Aula 1 - Python - Inteligencia Artificial Aplicada

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7AaHR5LRhU4-BangDYQ9NdVRncwcS5X

# **Aula 1**
"""

print("Hola mundo "+ "como estan?")

print("Hola mundo "+"25")

print(20+15)

20+15

producto_1= "Chocolate"
producto_2= "Pizza"
producto_3= "Celular"

print("Productos")
print("Producto 1: "+producto_1+" Producto 2: "+producto_2+ " Producto 3: "+producto_3)

total_de_compra = producto_1 + " "+ producto_2 + " "+ producto_3
print("Total de la compra: "+total_de_compra)

amigos = 6
alquiler = 900
supermercado = 500
vehiculo = 400

total = alquiler + supermercado + vehiculo
print("El total inicial del viaje es:",total)


alquiler = 800
total = alquiler + supermercado + vehiculo
print("El total inicial del viaje es:",total)

alquiler=alquiler-100
print(alquiler)

total_vehiculos=vehiculo*2
print("Valor de vehiculos:",total_vehiculos)

total_final = alquiler+supermercado+total_vehiculos

print("Total Final:",total_final)

total_por_persona=total_final/amigos

print("Total por persona:",total_por_persona)

#NO puedo colocar mas de una palabra en el nombre de una variable
#total_por persona =1500

#NO puedo iniciar el nombre de una variable con un número
#5producto = "alfajor"

#NO puedo utilizar palabras reservadas en nombres de variables

#print="Hola"

# nomnbre_de_producto="alfajor"  # Nomenclatura preferida en Python
# nomnbre-de-producto="alfajor"
# nomnbreDeProducto="alfajor"

print("Tipo de dato de alquiler:", type(alquiler))
print("Tipo de dato de total_por_persona", type(total_por_persona))
print("Tipo de dato de producto_1", type(producto_1))

juan_tiene_licencia_de_conducir=True
juan_tiene_licencia_de_conducir=False

print("Juan tiene licencia de conducir?",juan_tiene_licencia_de_conducir)

print("Tipo de dato de Juan...",type(juan_tiene_licencia_de_conducir))

texto= "martIN bonino  de alUra "

print("Texto original:",texto)

print(texto.upper())
print(texto.lower())
print(texto.strip())

print("Texto sin los espacios repetidos en el medio")
print(texto.replace("  "," "))

print(texto)

print(texto.lower().strip().replace("  "," "))
print(texto)

texto=texto.lower().strip().replace("  "," ")

print(texto)

nombre=input("Ingrese su nombre")

print("Nombre:",nombre)

edad=int(input("Ingrese su edad"))

print("Edad:",edad)
print("Tipo:",type(edad))

print("El nombre es: "+nombre+" y la edad es de: "+str(edad))

print(f"El nombre es nombre y la edad es edad")
print(f"El nombre es {nombre} y la edad es {edad}")

nombre=input("Ingrese su nombre: ")
# edad=int(input("Ingrese su edad: "))


# if edad >=18:
#   print(f"{nombre} usted puede ingresar al establecimiento porque tiene {edad} años")
# else:
#   print(f"{nombre} usted no puede ingresar porque tiene {edad} años. Por lo tanto es menor de edad")

promedio = float(input("Ingrese su promedio"))

if promedio>=7:
  print(f"{nombre} ha aprobado con {promedio}")
elif promedio >=5 and promedio < 7:
  print(f"{nombre} va a recuperatorio con {promedio}")
else:
  print(f"{nombre} está aplazado con {promedio}")